# Generated by Django 5.2.16 on 2026-08-07 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='webinars/speakers/')),
                ('profile_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pre', 'Pre-webinar'), ('post', 'Post-webinar')], max_length=10)),
                ('title', models.CharField(max_length=240)),
                ('introduction', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('requires_registration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('webinar', 'kind', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-visited_at',),
                'indexes': [models.Index(fields=['visited_at', 'path'], name='website_sit_visited_ee83d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('rating', 'Rating (1–5)'), ('yes_no', 'Yes / No')], max_length=24)),
                ('choices', models.TextField(blank=True, help_text='For choice questions, enter one option per line.')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='website.survey')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('flyer', models.ImageField(blank=True, upload_to='webinars/flyers/')),
                ('description', models.TextField()),
                ('starts_at', models.DateTimeField(verbose_name='date and time')),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited registrations.', null=True)),
                ('meeting_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('popup_enabled', models.BooleanField(default=False, help_text='Occasionally promote this webinar in a modal on the public website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speakers', models.ManyToManyField(blank=True, related_name='webinars', to='website.speaker')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='website.webinar'),
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('job_title', models.CharField(blank=True, max_length=160)),
                ('expectations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('consent_to_updates', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='website.webinar')),
            ],
            options={
                'ordering': ('-registered_at',),
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='website.survey')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='website.webinarregistration')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='website.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='website.surveyresponse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('response', 'question'), name='unique_response_question_answer')],
            },
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['is_published', 'starts_at'], name='website_web_is_publ_caacef_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['popup_enabled', 'starts_at'], name='website_web_popup_e_9f3973_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarregistration',
            index=models.Index(fields=['webinar', 'status'], name='website_web_webinar_7d7fd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='webinarregistration',
            constraint=models.UniqueConstraint(fields=('webinar', 'email'), name='unique_webinar_registration_email'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('survey', 'email'), name='unique_survey_response_email'),
        ),
    ]
